name: Tancredi APIs Test

# Controls when the action will run. Triggers the workflow on pull request for the master branch
on: [push, pull_request]

jobs:
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      
     
    # Install packages needed on runner
    - name: Install required packages
      run: sudo apt-get install -y apache2 bats
      
    # download and explode tancredi tarball
    - name: explode Tancredi
      run: |
        wget $(grep Source1 nethserver-tancredi.spec | rev | awk '{print $1}' | rev)
        mkdir tancredi
        tar xzpf tancredi.tar.gz -C tancredi --strip-components=1
        cd tancredi
        composer install --no-dev
        rm -v src/Entity/SampleFilter.php
        sudo mkdir -p /usr/share/tancredi/data/
        sudo cp -a {public,scripts,src,vendor}/ /usr/share/tancredi/
        sudo cp -a data/{templates,patterns.d,scopes} /usr/share/tancredi/data/
        sudo mkdir -p /var/lib/tancredi/data/{first_access_tokens,scopes,templates-custom,tokens,firmware}
        echo 'rw_dir = "/var/lib/tancredi/data/"' | sudo tee -a /etc/tancredi.conf
        echo 'ro_dir = "/usr/share/tancredi/data/"' | sudo tee -a /etc/tancredi.conf
        echo 'provisioning_url_path = "/provisioning/"' | sudo tee -a /etc/tancredi.conf
        echo 'api_url_path = "/tancredi/api/v1/"' | sudo tee -a /etc/tancredi.conf
        echo 'file_reader = "apache"' | sudo tee -a /etc/tancredi.conf

        cd ..

    - name: configure httpd
      run: |
        echo '<Location "/provisioning">' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        echo '    ProxyPass "/usr/share/tancredi/public/provisioning.php"' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        echo '</Location>' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        echo '<Location "/tancredi/api/v1">' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        echo '    ProxyPass "/usr/share/tancredi/public/api-v1.php"' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        echo '</Location>' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        echo 'XSendFile on' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        echo 'XSendFilePath /var/lib/tancredi/data/firmware' | sudo tee -a /etc/apache2/sites-available/tancredi.conf
        sudo a2ensite tancredi.conf
        sudo a2dissite 000-default.conf
        sudo systemctl restart apache2

    - name: run bats
      run: ./run.sh


